// -----------------------------------------------------------------------------
// FILE:	    Constants.cs
// CONTRIBUTOR: NEONFORGE Team
// COPYRIGHT:   Copyright © 2005-2024 by NEONFORGE LLC.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace Neon.Operator.Analyzers
{
    internal static class Constants
    {
        public const string AutoGeneratedHeader = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the NeonFORGE Operator SDK.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------";
        public const string ObjectTypeString = "object";
        public const string StringTypeString = "string";
        public const string BooleanTypeString = "boolean";
        public const string IntegerTypeString = "integer";
        public const string NumberTypeString = "number";
        public const string ArrayTypeString = "array";
        public const string Int32TypeString = "int32";
        public const string Int64TypeString = "int64";
        public const string FloatTypeString = "float";
        public const string DoubleTypeString = "double";
        public const string DateTimeTypeString = "date-time";
    }
}
