changelog:
  categories:
    - title: ✨ Implemented enhancements
      labels: 
        - enhancement
    - title: 🐛 Fixed bugs
      labels: 
        - bug        
    - title: 📝 Documentation updates
      labels: 
        - documentation
    - title: 🔨 Other
      labels: 
        - '*'
      exclude:
        labels:
          - enhancement
          - bug
          - documentation
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
