<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Test.Analyzers</RootNamespace>
        <IsPackable>false</IsPackable>
        <AssemblyName>Test.Analyzers</AssemblyName>
        <Configurations>Debug;Release</Configurations>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <NeonOperatorGenerateRbac>False</NeonOperatorGenerateRbac>
        <NeonOperatorGenerateCrds>False</NeonOperatorGenerateCrds>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <NeonOperatorCrdOutputDir>Generated/CRDs</NeonOperatorCrdOutputDir>
        <NeonOperatorRbacOutputDir>Generated/RBAC</NeonOperatorRbacOutputDir>
        <NeonOperatorWebhookOutputDir>Generated/Manifests</NeonOperatorWebhookOutputDir>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="CRDs\servicemonitor.yaml" />
        <Compile Remove="Models\*;Controllers\*" />
        <EmbeddedResource Include="Models\*;Outputs\*;CRDs\*;Controllers\*" CopyToOutputDirectory="Always" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="nuget-icon.png" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="xunit.runner.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="nuget-icon.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Microsoft.TestPlatform.TestHost" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.CodeAnalysis" />
        <PackageReference Include="coverlet.collector">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.extensibility.core" />
        <PackageReference Include="xunit.extensibility.execution" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
        <PackageReference Include="Microsoft.Rest.ClientRuntime" />
        <PackageReference Include="NJsonSchema" />
        <PackageReference Include="SystemTextJson.JsonDiffPatch" />
    </ItemGroup>

    <!-- NEONFORGE package or project references -->

    <Import Project="$(NO_ROOT)\src\Neon.Operator\build\Neon.Operator.targets" />

    <Choose>
        <When Condition="'$(NeonBuildUseNugets)' == 'true'">
            <ItemGroup>
                <PackageReference Include="Neon.Common" />
                <PackageReference Include="Neon.Roslyn" />
                <PackageReference Include="Neon.Roslyn.Xunit" />
                <PackageReference Include="Neon.Xunit" />
            </ItemGroup>
        </When>
        <Otherwise>
            <ItemGroup>
                <ProjectReference Include="$(NF_ROOT)\Lib\Neon.Common\Neon.Common.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
                <ProjectReference Include="$(NF_ROOT)\Lib\Neon.Roslyn\Neon.Roslyn.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
                <ProjectReference Include="$(NF_ROOT)\Lib\Neon.Roslyn.Xunit\Neon.Roslyn.Xunit.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
                <ProjectReference Include="$(NF_ROOT)\Lib\Neon.Xunit\Neon.Xunit.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
            </ItemGroup>
        </Otherwise>
    </Choose>

    <ItemGroup>
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Operator\Neon.Operator.csproj" />
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Operator.Analyzers\Neon.Operator.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Operator.Core\Neon.Operator.Core.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Operator.OperatorLifecycleManager\Neon.Operator.OperatorLifecycleManager.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Kubernetes.Core\Neon.Kubernetes.Core.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Kubernetes.Resources\Neon.Kubernetes.Resources.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    </ItemGroup>


</Project>
