<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <Configurations>Debug;Release</Configurations>
        <Description>Kubernetes Operator SDK.</Description>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageProjectUrl>https://docs.neonforge.com/docs/operator-sdk</PackageProjectUrl>
        <RepositoryUrl>https://github.com/nforgeio/operator-sdk</RepositoryUrl>
        <PackageIcon>nuget-icon.png</PackageIcon>
        <IsPackable>true</IsPackable>
        <RepositoryType>git</RepositoryType>
        <PackageTags>kubernetes operator sdk neonkube k8s</PackageTags>
        <PackageReleaseNotes>https://github.com/nforgeio/operator-sdk/releases</PackageReleaseNotes>
        <DebugType>full</DebugType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CompareNETObjects" />
        <PackageReference Include="KubernetesClient" />
        <PackageReference Include="KubernetesClient.Models" />
        <PackageReference Include="Microsoft.AspNetCore.JsonPatch" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Rest.ClientRuntime" />
        <PackageReference Include="NgrokSharp" />
        <PackageReference Include="NJsonSchema" />
        <PackageReference Include="prometheus-net" />
        <PackageReference Include="prometheus-net.AspNetCore" />
        <PackageReference Include="prometheus-net.AspNetCore.HealthChecks" />
        <PackageReference Include="SystemTextJson.JsonDiffPatch" />
    </ItemGroup>

    <!-- NEONFORGE package or project references -->

    <Choose>
        <When Condition="'$(NeonBuildUseNugets)' == 'true'">
            <ItemGroup>
                <PackageReference Include="Neon.Common" />
            </ItemGroup>
        </When>
        <Otherwise>
            <ItemGroup>
                <ProjectReference Include="$(NF_ROOT)\Lib\Neon.Common\Neon.Common.csproj" />
            </ItemGroup>
        </Otherwise>
    </Choose>

    <ItemGroup>
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Kubernetes\Neon.Kubernetes.csproj" />
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Operator.Analyzers\Neon.Operator.Analyzers.csproj" />
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Operator.Core\Neon.Operator.Core.csproj" />
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Kubernetes.Resources\Neon.Kubernetes.Resources.csproj" />
        <ProjectReference Include="$(NO_ROOT)\src\Neon.Operator.OperatorLifecycleManager\Neon.Operator.OperatorLifecycleManager.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\nuget-icon.png" Pack="true" PackagePath="" />
        <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
        <None Include="build\*" Pack="true" PackagePath="build\" />
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>
    
</Project>
